parameters:
#    practise_chart.example.class: Rosia\ChartBundle\Example

services:
#    Rosia_chart.example:
#        class: %practise_chart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
